### ISSUE TITLE
No file with name: hf_model_0001.pt

### ISSUE THREAD

**Issue by deepmindby** [ekinakyurek/marc#4]
Thank you for your excellent research and for sharing your work through this repository. I really appreciate the effort and thoughtfulness that went into this project—it’s truly impressive.

I have downloaded all the pre-trained models and carefully followed the provided instructions. However, while attempting to reproduce the results, I encountered the following error (details below). I would greatly appreciate it if you could provide any guidance or suggestions on how to resolve this issue. Thank you in advance for your help!

(arc) haichao@node01:~/zby/TTT/marc$ ./train_TTT.sh
UNMASK TOKENS IN CURRENT MODE
Number of train tasks:  15
Ignoring lora_to_output for llama3_2
{'model': {'_component_': 'torchtune.models.llama3_2.lora_llama3_2_1b', 'lora_attn_modules': ['q_proj', 'v_proj'], 'apply_lora_to_mlp': True, 'lora_rank': 128, 'lora_alpha': 16.0, 'lora_dropout': 0.0}, 'tokenizer': {'_component_': 'torchtune.models.llama3.llama3_tokenizer', 'path': 'models/meta-llama-1b/original/tokenizer.model', 'max_seq_len': None}, 'checkpointer': {'_component_': 'torchtune.training.FullModelHFCheckpointer', 'checkpoint_dir': '/home/haichao/zby/TTT/marc/models/marc-8B-finetuned-llama3', 'checkpoint_files': ['hf_model_0001.pt'], 'recipe_checkpoint': None, 'output_dir': '/home/haichao/zby/TTT/marc-checkpoints/experiments/lora/model_weights/', 'model_type': 'LLAMA3'}, 'resume_from_checkpoint': False, 'save_adapter_weights_only': True, 'dataset': {'_component_': 'torchtune.datasets.arc_dataset', 'source': 'data/dummy/', 'train_on_input': False, 'unmask_outputs': True}, 'seed': 0, 'shuffle': True, 'batch_size': 2, 'optimizer': {'_component_': 'torch.optim.AdamW', 'fused': True, 'weight_decay': 0.01, 'lr': 5e-05}, 'lr_scheduler': {'_component_': 'torchtune.training.lr_schedulers.get_cosine_schedule_with_warmup', 'num_warmup_steps': 5}, 'loss': {'_component_': 'torch.nn.CrossEntropyLoss'}, 'epochs': 2, 'max_steps_per_epoch': None, 'gradient_accumulation_steps': 1, 'compile': False, 'output_dir': '/home/haichao/zby/TTT/marc-checkpoints/experiments/lora', 'metric_logger': {'_component_': 'torchtune.training.metric_logging.DiskLogger', 'log_dir': '${output_dir}'}, 'log_every_n_steps': 1, 'log_peak_memory_stats': False, 'device': 'cuda', 'dtype': 'bf16', 'enable_activation_checkpointing': True, 'enable_activation_offloading': False, 'profiler': {'_component_': 'torchtune.training.setup_torch_profiler', 'enabled': False, 'output_dir': '${output_dir}/profiling_outputs', 'cpu': True, 'cuda': True, 'profile_memory': False, 'with_stack': False, 'record_shapes': True, 'with_flops': False, 'wait_steps': 5, 'warmup_steps': 5, 'active_steps': 2, 'num_cycles': 1}}
Augmenters to apply:  [Rotate(90), Rotate(270), Rotate(180), Flip(0), Flip(1), Reflect(0, reverse=True), Reflect(1, reverse=True), Reflect(0, reverse=False), Reflect(1, reverse=False), RandomTranslateXY(), Transpose(), IncreaseResolution(2), IncreaseHeight(2), IncreaseWidth(2), Chain([Rotate(90), IncreaseResolution(2)]), Chain([Rotate(270), IncreaseResolution(2)]), Chain([Rotate(180), IncreaseResolution(2)]), Chain([Flip(0), IncreaseResolution(2)]), Chain([Flip(1), IncreaseResolution(2)]), Chain([Transpose(), IncreaseResolution(2)]), Repeat(0, 2), Repeat(1, 2), Repeat(2, 2)] len:  23
DEBUG:torchtune.utils._logging:Setting manual seed to local seed 0. Local seed is seed + rank = 0 + 0
Writing logs to /home/haichao/zby/TTT/marc-checkpoints/experiments/lora/log_1733386488.txt
Traceback (most recent call last):
  File "/home/haichao/zby/TTT/marc/test_time_train.py", line 333, in <module>
    recipe.setup(cfg=conf)
  File "/home/haichao/zby/TTT/marc/third_party/torchtune/recipes/lora_finetune_single_device.py", line 236, in setup
    checkpoint_dict = self.load_checkpoint(cfg_checkpointer=cfg.checkpointer)
  File "/home/haichao/zby/TTT/marc/third_party/torchtune/recipes/lora_finetune_single_device.py", line 169, in load_checkpoint
    self._checkpointer = config.instantiate(
  File "/home/haichao/zby/TTT/marc/third_party/torchtune/torchtune/config/_instantiate.py", line 112, in instantiate
    return _instantiate_node(OmegaConf.to_object(config), *args)
  File "/home/haichao/zby/TTT/marc/third_party/torchtune/torchtune/config/_instantiate.py", line 33, in _instantiate_node
    return _create_component(_component_, args, kwargs)
  File "/home/haichao/zby/TTT/marc/third_party/torchtune/torchtune/config/_instantiate.py", line 22, in _create_component
    return _component_(*args, **kwargs)
  File "/home/haichao/zby/TTT/marc/third_party/torchtune/torchtune/training/checkpointing/_checkpointer.py", line 355, in __init__
    self._checkpoint_paths = self._validate_hf_checkpoint_files(checkpoint_files)
  File "/home/haichao/zby/TTT/marc/third_party/torchtune/torchtune/training/checkpointing/_checkpointer.py", line 396, in _validate_hf_checkpoint_files
    checkpoint_path = get_path(self._checkpoint_dir, f)
  File "/home/haichao/zby/TTT/marc/third_party/torchtune/torchtune/training/checkpointing/_utils.py", line 165, in get_path
    raise ValueError(f"No file with name: {filename} found in {input_dir}.")
ValueError: No file with name: hf_model_0001.pt found in /home/haichao/zby/TTT/marc/models/marc-8B-finetuned-llama3.

**Comment by kungfu-eric** [comment]
Your config is off, that's for the barc model. Check the configs folder, should be something like
```
  checkpoint_files: [
     pytorch_model-0001-of-0004.bin,
     pytorch_model-0002-of-0004.bin,
     pytorch_model-0003-of-0004.bin,
     pytorch_model-0004-of-0004.bin,
  ]
```

**Comment by deepmindby** [comment]
Thank you for your response and guidance!

I have kept the format you mentioned in configs/pretrain/8B_full.yaml and 8B_lora_single_device.yaml, as shown below:

``` 
checkpoint_files: [
     pytorch_model-0001-of-0004.bin,
     pytorch_model-0002-of-0004.bin,
     pytorch_model-0003-of-0004.bin,
     pytorch_model-0004-of-0004.bin,
  ]
```
However, the issue still persists. Specifically, the filename in the get_path function in _utils.py always resolves to hf_model_0001.pt.

Could you kindly advise on how to resolve this problem? I greatly appreciate your help!

**Comment by ekinakyurek** [comment]
I see that you are using Llama3.2 1B model `torchtune.models.llama3_2.lora_llama3_2_1b`, so you need to edit this file instead `https://github.com/ekinakyurek/marc/blob/main/configs/pretrain/1B_full.yaml` to conform your file paths.

**Comment by deepmindby** [comment]
Thank you for your prompt response! The issue has been resolved. 😊
